# Stripper Configuration File

# Crawler settings
crawler:
  # Maximum depth to crawl (default: 1)
  depth: 2
  
  # Output format: markdown, text, or html (default: markdown)
  format: "markdown"
  
  # Output directory for crawled content (default: output)
  output_dir: "output"
  
  # File extensions to ignore during crawling
  ignore_extensions:
    - pdf
    - jpg
    - png
    - gif
    - zip
    - exe
    - doc
    - docx
    - xls
    - xlsx

  # Rescan interval for previously crawled pages (e.g., 24h, 1h30m, 15m)
  # Pages older than this will be recrawled to check for changes
  rescan_interval: "24h"

# HTTP client settings
http:
  # Request timeout in seconds
  timeout: 30
  
  # Number of retry attempts for failed requests
  retry_attempts: 3
  
  # Delay between retries in seconds
  retry_delay: 5
  
  # User agent string for requests
  user_agent: "Stripper/1.0 Web Content Crawler"
  
  # Delay between requests in milliseconds (to be nice to servers)
  request_delay: 1000
