name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Install basic tools and cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential tar wget git
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y gcc-multilib g++-multilib

      - name: Install OSXCross
        run: |
          # Install OSXCross dependencies
          sudo apt-get install -y clang llvm-dev libxml2-dev uuid-dev libssl-dev bash patch make tar xz-utils bzip2 gzip sed cpio libbz2-dev

          # Get OSXCross
          git clone https://github.com/tpoechtrager/osxcross
          cd osxcross

          # Get MacOS SDK
          wget -q https://github.com/joseluisq/macosx-sdks/releases/download/12.3/MacOSX12.3.sdk.tar.xz -O tarballs/MacOSX12.3.sdk.tar.xz

          # Build OSXCross (takes a while)
          UNATTENDED=1 ./build.sh

          # Add to PATH
          echo "$PWD/target/bin" >> $GITHUB_PATH

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1
          PATH: /usr/lib/ccache:/usr/local/opt/ccache/libexec:${{ github.workspace }}/osxcross/target/bin:${{ env.PATH }}
