name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            crossbuild-essential-arm64 \
            libsqlite3-dev:arm64 \
            libsqlite3-dev \
            clang llvm

      - name: Set up cross-compilation environment
        run: |
          echo "GOOS=linux" >> $GITHUB_ENV
          echo "GOARCH=arm64" >> $GITHUB_ENV
          echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CXX=aarch64-linux-gnu-g++" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
          echo "Adding cross-compiler to PATH"
          echo "/usr/aarch64-linux-gnu/bin" >> $GITHUB_PATH

      - name: Set up OSXCross for macOS cross-compilation
        run: |
          mkdir -p /tmp/osxcross
          cd /tmp/osxcross
          wget https://github.com/tpoechtrager/osxcross/archive/refs/heads/master.tar.gz
          tar xzf master.tar.gz
          cd osxcross-master
          wget -P tarballs https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          UNATTENDED=yes OSX_VERSION_MIN=10.15 ./build.sh
          echo "/tmp/osxcross/osxcross-master/target/bin" >> $GITHUB_PATH

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
