name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          sudo apt-get install -y gcc-multilib g++-multilib
          # Install OSXCross for macOS cross-compilation
          mkdir -p /tmp/osxcross
          cd /tmp/osxcross
          wget -q https://github.com/tpoechtrager/osxcross/archive/refs/heads/master.tar.gz
          tar xf master.tar.gz
          cd osxcross-master
          wget -q https://github.com/joseluisq/macosx-sdks/releases/download/12.3/MacOSX12.3.sdk.tar.xz
          mv MacOSX12.3.sdk.tar.xz tarballs/
          UNATTENDED=1 ./build.sh
          echo "/tmp/osxcross/osxcross-master/target/bin" >> $GITHUB_PATH

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1
