name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Install Linux cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-multilib g++-multilib \
            gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

          echo "/usr/bin" >> $GITHUB_PATH  # Ensure toolchain is in PATH
          which aarch64-linux-gnu-gcc && aarch64-linux-gnu-gcc --version

      - name: Install macOS cross-compilation tools (osxcross)
        run: |
          sudo apt-get install -y clang llvm-dev libxml2-dev uuid-dev libssl-dev bash patch make tar xz-utils bzip2 gzip sed cpio libbz2-dev

          git clone https://github.com/tpoechtrager/osxcross.git
          cd osxcross

          wget -q https://github.com/joseluisq/macosx-sdks/releases/download/12.3/MacOSX12.3.sdk.tar.xz -O tarballs/MacOSX12.3.sdk.tar.xz

          UNATTENDED=1 ./build.sh

          echo "$PWD/target/bin" >> $GITHUB_PATH

      - name: Verify Compiler Availability
        run: |
          which aarch64-linux-gnu-gcc || echo "aarch64-linux-gnu-gcc NOT FOUND"
          which x86_64-apple-darwin20-clang || echo "macOS Clang NOT FOUND"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1
          PATH: /usr/lib/ccache:/usr/local/opt/ccache/libexec:${{ env.PATH }}
